### ISSUE TITLE
Syria EM | Conflict Trends Update

### ISSUE THREAD

**Issue by Holly-Transport** [datapartnership/syria-economic-monitor#71]
***An update of existing analysis\*** 

 

·    Conflict-related events and deaths by governorate and areas of control.

**Comment by SahitiSarva** [comment]
The old conflict notebook for Syria shows the update for post earthquake analysis. I think the best way to do this update would be to create a new notebook for this version. You can copy over the [sample notebook](https://github.com/datapartnership/acled_conflict_analysis/blob/main/notebooks/acled.ipynb) in the `acled_conflict_analysis` package that is now available.

**Comment by dmatekenya** [comment]
The conflict in Syria started in 2011 but some of the notebooks start the trends analysis at 2017, should I start from 2017? and up to now? I will start from 2017 to now and update later if need be.

**Comment by SahitiSarva** [comment]
Updates from 15th October Check-In:

**Conflict:** @dmatekenya 
- Change the yearly trends to show beginning of the year and not the end
- Go back to 2017, change it from being a cumulative map to a make radio button that allows them to change it
- Lay over the data over a control map provided by Luan's team
- What does the influx of refugees from Lebanon mean for the conflict landscape in Syria? They want to spatially visualize the extent to which any violent events can be traced to where the refugees are. 
- Is there a seasonality in the conflict trend where it dips every February?

**Comment by SahitiSarva** [comment]
@dmatekenya -- Luan mentioned on call today that they might do this analysis on their own. Will confirm again on Thursday.

**Comment by SahitiSarva** [comment]
Luan's team did not require a conflict analysis for the next update from us.
