### ISSUE TITLE
Conflict Analysis

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/syria-economic-monitor#85]
Found a few bugs in the conflict notebook - 
1. The chart titles are still the dummy titles from the package, they need to be changed
2. The data is available from 2017 but only data from 2020 October was used (this was because of an issue with the extraction package which @SahitiSarva has fixed). Could we rerun the analysis from January 2020 or from 2017 January?
3. The previous update had a chart with breakdown by governorate, we need to add that this time also because this needs to be an update
4. The stacked bar chart is probably not required for this analysis and can be removed.

**Comment by dmatekenya** [comment]
Resolving these now and will ping you once I have pushed the changes.

**Comment by dmatekenya** [comment]
Yes, I did like that line chart and was thinking of adding it later.
